# Generated by Django 4.2.5 on 2023-09-09 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('done', 'Done'), ('canceled', 'Canceled')], default='new', help_text='Status of order', max_length=255, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('done', 'Done'), ('canceled', 'Canceled')], default='new', help_text='Status of history', max_length=255, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time of history created', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date and time of history updated', verbose_name='Updated')),
                ('order', models.ForeignKey(help_text='Order of history', on_delete=django.db.models.deletion.CASCADE, to='app.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order history',
                'verbose_name_plural': 'Order histories',
                'ordering': ('-id',),
            },
        ),
    ]
