# Generated by Django 4.2.5 on 2023-09-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_status_orderhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botuser',
            old_name='added',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='botuser',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='orderfile',
            old_name='added',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='orderhistory',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='orderhistory',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='botuser',
            name='full_name_en',
            field=models.CharField(blank=True, help_text='Full name of user', max_length=255, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='full_name_ru',
            field=models.CharField(blank=True, help_text='Full name of user', max_length=255, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='full_name_uz',
            field=models.CharField(blank=True, help_text='Full name of user', max_length=255, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(help_text='Name of category', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(help_text='Name of category', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(help_text='Name of category', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='comment',
            name='body_en',
            field=models.TextField(help_text='Body of comment', null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='comment',
            name='body_ru',
            field=models.TextField(help_text='Body of comment', null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='comment',
            name='body_uz',
            field=models.TextField(help_text='Body of comment', null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='order',
            name='description_en',
            field=models.TextField(help_text='Description of order', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='order',
            name='description_ru',
            field=models.TextField(help_text='Description of order', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='order',
            name='description_uz',
            field=models.TextField(help_text='Description of order', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_en',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('done', 'Done'), ('canceled', 'Canceled')], default='new', help_text='Status of order', max_length=255, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_ru',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('done', 'Done'), ('canceled', 'Canceled')], default='new', help_text='Status of order', max_length=255, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_uz',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('done', 'Done'), ('canceled', 'Canceled')], default='new', help_text='Status of order', max_length=255, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='status_en',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('done', 'Done'), ('canceled', 'Canceled')], default='new', help_text='Status of history', max_length=255, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='status_ru',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('done', 'Done'), ('canceled', 'Canceled')], default='new', help_text='Status of history', max_length=255, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='status_uz',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('done', 'Done'), ('canceled', 'Canceled')], default='new', help_text='Status of history', max_length=255, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(help_text='Name of subcategory', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ru',
            field=models.CharField(help_text='Name of subcategory', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_uz',
            field=models.CharField(help_text='Name of subcategory', max_length=255, null=True, verbose_name='Name'),
        ),
    ]
