# Generated by Django 4.2.5 on 2023-09-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_botuser_full_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='position',
            field=models.CharField(blank=True, help_text='Position of user', max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='workplace',
            field=models.CharField(blank=True, help_text='Workplace of user', max_length=255, null=True, verbose_name='Workplace'),
        ),
    ]
