# Generated by Django 4.2.5 on 2023-09-13 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order_name_order_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_provider', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('cash', 'Cash')], default='click', help_text='Payment provider of payment history', max_length=20, verbose_name='Payment provider')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of payment history', max_digits=10, verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time of payment history created', verbose_name='Created at')),
                ('order', models.ForeignKey(help_text='Order of payment history', on_delete=django.db.models.deletion.CASCADE, to='app.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Payment history',
                'verbose_name_plural': 'Payment histories',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of item', max_length=255, verbose_name='Name')),
                ('duration', models.IntegerField(help_text='Duration of item', verbose_name='Duration')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of item', max_digits=10, verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time of item created', verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of item updated', verbose_name='Updated')),
                ('order', models.ForeignKey(help_text='Order of item', on_delete=django.db.models.deletion.CASCADE, to='app.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order item',
                'verbose_name_plural': 'Order items',
                'ordering': ('-id',),
            },
        ),
    ]
