# Generated by Django 4.2.5 on 2023-09-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_order_name_paymenthistory_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', "Ko'rib chiqilmoqda"), ('in_progress', 'Tayyorlanmoqda'), ('done', 'Tayyor'), ('canceled', 'Bekor qilingan')], default='new', help_text='Status of order', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_en',
            field=models.CharField(choices=[('new', "Ko'rib chiqilmoqda"), ('in_progress', 'Tayyorlanmoqda'), ('done', 'Tayyor'), ('canceled', 'Bekor qilingan')], default='new', help_text='Status of order', max_length=255, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_ru',
            field=models.CharField(choices=[('new', "Ko'rib chiqilmoqda"), ('in_progress', 'Tayyorlanmoqda'), ('done', 'Tayyor'), ('canceled', 'Bekor qilingan')], default='new', help_text='Status of order', max_length=255, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_uz',
            field=models.CharField(choices=[('new', "Ko'rib chiqilmoqda"), ('in_progress', 'Tayyorlanmoqda'), ('done', 'Tayyor'), ('canceled', 'Bekor qilingan')], default='new', help_text='Status of order', max_length=255, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('new', "Ko'rib chiqilmoqda"), ('in_progress', 'Tayyorlanmoqda'), ('done', 'Tayyor'), ('canceled', 'Bekor qilingan')], default='new', help_text='Status of history', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status_en',
            field=models.CharField(choices=[('new', "Ko'rib chiqilmoqda"), ('in_progress', 'Tayyorlanmoqda'), ('done', 'Tayyor'), ('canceled', 'Bekor qilingan')], default='new', help_text='Status of history', max_length=255, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status_ru',
            field=models.CharField(choices=[('new', "Ko'rib chiqilmoqda"), ('in_progress', 'Tayyorlanmoqda'), ('done', 'Tayyor'), ('canceled', 'Bekor qilingan')], default='new', help_text='Status of history', max_length=255, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status_uz',
            field=models.CharField(choices=[('new', "Ko'rib chiqilmoqda"), ('in_progress', 'Tayyorlanmoqda'), ('done', 'Tayyor'), ('canceled', 'Bekor qilingan')], default='new', help_text='Status of history', max_length=255, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_provider',
            field=models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('cash', 'Naqd')], default='click', help_text='Payment provider of payment history', max_length=20, verbose_name='Payment provider'),
        ),
    ]
